apiVersion: v1
kind: List
items:
- kind: Secret
  apiVersion: v1
  metadata:
    namespace: {{namespace}}
    name: postgres-auth
  type: Opaque
  data:
    password: '{{postgres_password}}'
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: {{namespace}}
    name: postgres
  spec:
    replicas: 1
    template:
      metadata:
        namespace: {{namespace}}
        labels:
          name: postgres
      spec:
        containers:
        - name: postgres
          image: {{repo}}/polykube-postgres:{{version}}
          imagePullPolicy: Always
          volumeMounts:
          - name: postgres-auth-secret
            mountPath: /etc/polykube/postgres-auth
            readOnly: true
          ports:
          - containerPort: 80
        volumes:
        - name: postgres-auth-secret
          secret:
            secretName: postgres-auth
- kind: Service
  apiVersion: v1
  metadata:
    namespace: {{namespace}}
    name: postgres
  spec:
    selector:
      name: postgres
    ports:
    - port: 5432
      targetPort: 5432
