apiVersion: v1
kind: List
items:
- kind: Secret
  apiVersion: v1
  metadata:
    namespace: {{namespace}}
    name: redis-auth
  type: Opaque
  data:
    password: '{{redis_password}}'
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: {{namespace}}
    name: redis
  spec:
    replicas: 1
    template:
      metadata:
        namespace: {{namespace}}
        labels:
          name: redis
      spec:
        containers:
        - name: redis
          image: {{repo}}/polykube-redis:{{version}}
          imagePullPolicy: Always
          volumeMounts:
          - name: redis-auth-secret
            mountPath: /etc/polykube/redis-auth
            readOnly: true
          ports:
          - containerPort: 6379
        volumes:
        - name: redis-auth-secret
          secret:
            secretName: redis-auth
- kind: Service
  apiVersion: v1
  metadata:
    namespace: {{namespace}}
    name: redis
  spec:
    selector:
      name: redis
    ports:
    - port: 6379
      targetPort: 6379
